# This is a basic workflow to help you get started with Actions
name: Fibonacci Sequence

on:
  push:
    branches:
      - main

jobs:
  fibonacci-sequence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count commits
        id: commit-count
        run: echo "::set-output name=count::$(git rev-list --count HEAD)"

      - name: Generate Fibonacci sequence
        id: fibonacci-sequence
        run: |
          commits=$(echo "${{ steps.commit-count.outputs.count }}")
          a=0
          b=1
          fibonacci=0
          sequence=""
          for ((i=0; i<$commits; i++)); do
            sequence="$sequence $fibonacci"
            fibonacci=$((a + b))
            a=$b
            b=$fibonacci
          done
          echo "::set-output name=sequence::$sequence"

